version: 2.1
jobs:
  Installation:
    docker:
      - image: circleci/node:12.9-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - npm-packages
      - run:
          name: Install Node Modules
          command : npm install
      - run:
          name: Install Expo CLI
          command : npm install expo-cli
      - save_cache:
          paths:
            - node_modules
          key: npm-packages-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  Docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:  Dockerize
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Publish to DockerHub
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker tag app $DOCKER_HUB_USERNAME/tp-final-devops-front:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USERNAME/tp-final-devops-front:latest
            docker push $DOCKER_HUB_USERNAME/tp-final-devops-front:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USERNAME/tp-final-devops-front:latest
workflows:
  Installa_and_Dockerize:
    jobs:
      - Installation
      - Docker:
          context: Docker
          requires:
            - Build
