version: 2.1
jobs:
  Installation:
    docker:
      - image: circleci/node:12.9-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - npm-packages
      - run:
          name: Install Node Modules
          command : npm install
      - run:
          name: Install Expo CLI
          command : npm install expo-cli
      - save_cache:
          paths:
            - node_modules
          key: npm-packages-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

workflows:
  Install_and_Dockerize:
    jobs:
      - Installation
